### ISSUE TITLE
Cannot read properties of undefined (reading 'texture')

### ISSUE THREAD

**Issue by NitramDom** [maitrungduc1410/vue-pixi-wrapper#21]
Using version 1.1.5 when i use AnimatedSprite

Error : client.js?06a0:103 TypeError: Cannot read properties of undefined (reading 'texture')

<img width="642" alt="Capture d’écran 2021-12-18 à 16 15 13" src="https://user-images.githubusercontent.com/15178824/146636017-653cde39-6694-4866-864d-62ff994cf4d8.png">
<img width="445" alt="Capture d’écran 2021-12-18 à 16 15 04" src="https://user-images.githubusercontent.com/15178824/146636021-16d7bf1b-85c7-43e0-9deb-66427b8747b6.png">
<img width="501" alt="Capture d’écran 2021-12-18 à 16 14 44" src="https://user-images.githubusercontent.com/15178824/146636023-3bc52a5e-f763-4d42-8f7b-348dd7dc022b.png">
<img width="675" alt="Capture d’écran 2021-12-18 à 16 14 33" src="https://user-images.githubusercontent.com/15178824/146636026-e6daf983-08ee-4f7b-a3a8-12973ef00a0c.png">

**Comment by maitrungduc1410** [comment]
Hi @NitramDom , pls install version `1.1.6` , I fixed this issue

**Comment by maitrungduc1410** [comment]
also notice that AnimatedSprite doesn't have props name `texture`, and you can pass `images` using `require` like this:

![Screenshot 2021-12-22 at 12 29 51 AM](https://user-images.githubusercontent.com/16630193/146966034-23bfcdcb-ee0a-463b-b221-7f4ee4d37619.png)

**Comment by NitramDom** [comment]
Thanks @maitrungduc1410, I will try it soon
